CREATE DATABASE bukutamu;

USE bukutamu;

CREATE TABLE tamu (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nama VARCHAR(100),
    email VARCHAR(100),
    pesan TEXT,
    tanggal TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
